services:
  nginx:
    image: nginx:1.29-alpine        # можно обновлять по необходимости
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_IP=${BACKEND_IP}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt:ro
    command: >
      /bin/sh -c "
      envsubst '\$${DOMAIN} \$${BACKEND_IP}' \
        < /etc/nginx/templates/site.conf.tmpl \
        > /etc/nginx/conf.d/site.conf &&
      exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "
      trap exit TERM;
      while :; do
        certbot certonly \
          --webroot -w /var/www/certbot \
          --email ${LE_EMAIL} --agree-tos --no-eff-email \
          -d ${DOMAIN} --non-interactive;
        # перезапускаем nginx, если сертификаты обновились
        nginx_pid=\$(docker inspect --format '{{.State.Pid}}' nginx 2>/dev/null || true);
        [ -n \"\$nginx_pid\" ] && kill -HUP \$nginx_pid || true;
        sleep 12h & wait \$${!};
      done"
      