services:
  nginx:
    image: nginx:1.29-alpine
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    environment:
      DOMAIN: ${DOMAIN}
      BACKEND_IP: ${BACKEND_IP}
    volumes:
      - ./scripts/nginx-entrypoint.sh:/entrypoint.sh:ro
      - ./scripts/render-http.sh:/render-http.sh:ro
      - ./scripts/render-https.sh:/render-https.sh:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: ["/entrypoint.sh"]

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      LE_EMAIL: ${LE_EMAIL}
    volumes:
      - ./scripts/render-https.sh:/render-https.sh:ro
      - ./scripts/certbot-loop.sh:/certbot-loop.sh:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: ["/certbot-loop.sh"]